; version=13
[path]
read-data=__PATH__executable__/../../data
write-data=/run/media/upsidedowneye/B4EAD25BEAD21986/Users/Upsidedowneye/Programs/Factorio/2.1/AI/

[general]
locale=auto

[other]
verbose-logging=false
autosave-slots=50
multiplayer-max-heartbeats-per-second=240
multiplayer-initial-connection-timeout=1000
multiplayer-max-connection-attempts-per-peer=1000
port=34197
enable-new-mods=false
non-blocking-saving=true
enable-blueprint-storage-cloud-sync=false
allow-manual-autosaves=true
enable-corrupt-position-recovery=true
move-character-to-editor-on-editor-exit=true
autosave-compression-level=maximum
